### ISSUE TITLE
Utilize trail descriptions from Benson’s guide?

### ISSUE THREAD

**Issue by joyrexus** [sewanee-carto/trails#4]
John Benson wrote [an article with descriptions of Sewanee's best day hikes](https://www.sewanee.edu/media/student-life/explore/Sewanees_Ten_Best_Day_Hikes.pdf).  Let's ask John if we can use this info for a web-based trail guide.  It shouldn't be that hard to extract out the relevant info and add it as a geojson feature (or set of features) for each of the described trails.

**Comment by joyrexus** [comment]
If we get permission, the first step will be extracting out the relevant info from the PDF.  This is largely just a matter of copy-and-paste.  [Here's a start on this](https://github.com/sewanee-carto/trails/blob/master/data/benson-guide/text.md).  

John provides 4 elements in each hike description that could be added as geojson features to the respective trail: `miles` (length of hike in miles), `route` (roundtrip or one-way), `directions` (where and how to access the trail), and `description` (a colorful description of what you'll see along the way).

@naskoap would you be willing to extract out the remaining hikes?

**Comment by naskoap** [comment]
@joyrexus please review #5.

**Comment by joyrexus** [comment]
Merged. Thanks!
